version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
